### ISSUE TITLE
Signature generation does not properly deal with parameters

### ISSUE THREAD

**Issue by SimonTouchtech** [AlexGhiondea/OAuth.net#4]
I have found two areas where the signature generation differs from the specification [section 3.4.1.3.1](https://tools.ietf.org/html/rfc5849#section-3.4.1.3.1):

1. The entity-body is not considered (see 3rd point in specification)
2. names and values are not decoded (see "names and values and decoding them as defined by [W3C.REC-html40-19980424], Section 17.13.4" and a similar sentence for entity-body)

I have implemented a fix for both these issues and will create a pull request for them.

**Comment by AlexGhiondea** [comment]
Hey. Thanks for spotting this! And thanks for the PR!

I am taking a look now (sorry -- I missed this notification until now).
