### ISSUE TITLE
oauth_version 1.0a is invalid

### ISSUE THREAD

**Issue by SimonTouchtech** [AlexGhiondea/OAuth.net#6]
In this code, the `oauth_version` parameter is set to 1.0a in the requests. However, the specification for OAuth 1 says that if present, the value MUST be 1.0 (even for OAuth 1.0a). I'm guessing there's a reason it was set to 1.0a and that some servers accept that value. 

I would suggest changing it to be 1.0 as all servers should be able to handle that, but otherwise making it possible to choose between 1.0 and 1.0a as the value might be an option.

**Comment by AlexGhiondea** [comment]
I think allowing it to be 1.0 or 1.0a is the best option. I don't remember a reason to have it be 1.0

**Comment by AlexGhiondea** [comment]
The only reason I can think of for keeping the existing behavior (sending 1.0a) is for back-compat.

**Comment by AlexGhiondea** [comment]
I changed this to be 1.0 as the default in the 1.5 release.
